name: Run and get videos
on: [push]
jobs:
  create_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instala node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Instala chrome
        run: npx @puppeteer/browsers install chrome@stable
      - name: Instala paquetería
        run: | 
          npm install --ignore-scripts
      - name: Corre app
        if: success()
        run: | 
          video=$(cat video.txt)
          node app.js $video
      - name: Muestra Output
        if: success()
        run: |
        for i in $video
        do cat $i
        done
      - name: Guarda Output
        if: success()
        run: |
          git config --global user.name 'christopherorea'
          git config --global user.email 'c28_09_98@hotmail.com'
          git checkout -b "output"
          git add .
          git commit -am "Nuevo Output"
          git push --force --set-upstream origin output