name: Run and get videos
on: [push]
jobs:
  run_node:
    runs-on: ubuntu-latest
    steps:
      - name: Instala node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Instala chrome
        run: npx @puppeteer/browsers install chrome@stable
      - name: Instala Puppeteer
        run: | 
          npm install --ignore-scripts puppeteer
      - name: Obtiene repo
        uses: actions/checkout@v4
      - name: Corre app
        run: | 
          node app.js ${{ github.event.head_commit.message }}
      - name: Muestra Output
        run: cat output.txt
      - name: Guarda Output
        uses: stefanzweifel/git-auto-commit-action@v4

             