name: Run and get videos
on: [push]
jobs:
  - name: Correr Node
    runs-on: ubuntu-latest
    steps:
      - name: Instala node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Instala chrome
        run: npx @puppeteer/browsers install chrome@stable
      - name: Guarda Chrome
        uses: actions/download-artifact@v3
        with:
          name: Guarda Chrome
          path: chrome
      - name: Corre node
        run: | 
          npm install --ignore-scripts puppeteer &&
          node .\app.js ${{ github.event.head_commit.message }}
      - name: Guarda Output
        uses: stefanzweifel/git-auto-commit-action@v4

             